version: '2'

services:
  webserver:
    build: ./webserver
    image: simple_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/fff-skeleton:/var/www
    links:
      - db:mysql

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - /var/www/fff-skeleton/local/app/db:/var/local/db
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=skeleton
      - MYSQL_USER=david
      - MYSQL_PASSWORD=myPassword
